### ISSUE TITLE
SyntaxError: Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid escape

### ISSUE THREAD

**Issue by Mankio** [eight04/wakfu-autobuild#8]
Command used (Second example provided in REAME.md): 
```wakfu-autobuild --level 140 --element 1 --require mp=2 --base-mastery 301 --base-critical-hit 11  --second-mastery singleTarget,melee --disable-category accessory --ap-to-damage```

System used : Ubuntu 18.04 LTS

Error :
```
SyntaxError: Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid escape
    at camelCase (/usr/local/lib/node_modules/wakfu-autobuild/node_modules/camelcase/index.js:69:3)
    at main (/usr/local/lib/node_modules/wakfu-autobuild/cli.js:67:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/wakfu-autobuild/cli.js:43:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by eight04** [comment]
It seems that camelcase requires node >= 10. What is your node version?

**Comment by Mankio** [comment]
v8.10.0
I just updated to v14.5.0, and it work perfectly fine now.

Sorry for the useless issue !
